### PR TITLE
4.9 generic patch

### PR DESCRIPTION
**Pull request by lazerl0rd**

### CODE REVIEW

**Comment by frogzhou** [comment]
How to use this patch?
The function hidg_bind_config() is called by no one. Maybe I missed something.

**Comment by Sohil876** [comment]
Any reason why this hasnt been merged yet? @pelya

**Comment by fasheng** [comment]
This patch works and you must enable HID gadget function in some place, here is my example:
https://github.com/fasheng/nethunter_kernel_lge_sdm845/commit/e74d3c43b4e3c74c7c1717c88266d4cedafe9b26

**Comment by lazerl0rd** [comment]
@fasheng @Sohil876 mind updating your kernels with the following change https://github.com/pelya/android-keyboard-gadget/pull/172?

Sorry for the bother.

**Comment by acai66** [comment]
- Missing break in case 0.
```
+		switch (opts->minor) {
+		case 0:
+			opts->subclass = ghid_device_android_keyboard.subclass;
+			opts->protocol = ghid_device_android_keyboard.protocol;
+			opts->report_length = ghid_device_android_keyboard.report_length;
+			opts->report_desc_length = ghid_device_android_keyboard.report_desc_length;
+			opts->report_desc = ghid_device_android_keyboard.report_desc;
+		case 1:
+			opts->subclass = ghid_device_android_mouse.subclass;
+			opts->protocol = ghid_device_android_mouse.protocol;
+			opts->report_length = ghid_device_android_mouse.report_length;
+			opts->report_desc_length = ghid_device_android_mouse.report_desc_length;
+			opts->report_desc = ghid_device_android_mouse.report_desc;
+		}
```

**Pull request merged**
